services:
  app:
    entrypoint:
    - sleep
    - infinity
    image: neuropixel-pipeline-dev:latest
    build:
      context: .
      dockerfile: Dockerfile.dev
    init: true
    volumes:
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock

