version: '3'
services:
  dev:
    image: neuropixel-pipeline-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file: .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock